apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: idrissdjio/converter
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret